### Задача 1

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [71]:
import numpy as np
from math import sqrt

In [72]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
zp*ks

array([ 14035,  25830, 166060, 183800,  18360,  51730,  35262, 135300,
        89520,  91520])

In [73]:
covcoeff = (zp*ks).mean() - zp.mean()*ks.mean()
covcoeff

9157.839999999997

In [74]:
# проверим с помощью встроенной функции из numpy
covcoef1 = np.cov(zp,ks, ddof = 0)
covcoef1

# значение совпадает с рассчитанным только при ddof=0,  т е при смещенном стандартном отклонении

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [75]:
# в знаменателе учитываем смещенное стаднартное отклонение

corrcoef = covcoef/(sqrt(np.var(zp))*sqrt(np.var(ks)))
corrcoef

0.8874900920739158

In [76]:
#Проверим, чтобы рассчитанное значение совпадало со значением, полученным по встроенной функции numpy
corrcoef1 = np.corrcoef(zp,ks)
corrcoef1

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

### Задача 2
Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [77]:
a = [131, 125, 115, 122, 131, 115, 107, 99, 125, 111]
alpha = 0.05
n = len(a)
X_mean = sum(a)/len(a)
std = sqrt(np.var(a, ddof = 1))

# т к отсутствует дисперсия, будем использовать  t-критерий Стъюдента

In [78]:
#найдем значение t-критерия для альфа = 0.05/2 = 0.025 и 9 степеней свободы
t = 2.262

In [79]:
interval = [X_mean - t*std/sqrt(n), X_mean + t*std/sqrt(n)]
interval

[110.55660776308164, 125.64339223691834]

### Задача 3
Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [80]:
D = 25
std = sqrt(D)
n = 27
X_mean = 174.2
alpha = 0.05

# Используем Z-критерий

In [81]:
# найдем Z критерий для a = 0.05/2 = 0.025
Z = 1.96

In [82]:
interval = [X_mean - Z*std/sqrt(n), X_mean + Z*std/sqrt(n)]
interval

[172.31398912064722, 176.08601087935276]

### Задача 4
Выберите тему для проектной работы по курсу Теории вероятностей и математической статистики

In [83]:
# Пока затрудняюсь с выбором темы для курсовой
# Наиболее привлекательны : EDA, тестирование гипотезы (пока не поняла, как это применить к датасету из kaggle)